[package]
name = "new"
version = "0.1.0"
authors = ["Connor Slade <connor@connorcode.com>"]
edition = "2018"

[dependencies]
iced = { version = "0.3", features = ["smol"] }
notify-rust = "4"
msgbox = "0.6.1"

[build-dependencies]
chrono = "0.4.19"