[package]
name = "new"
version = "0.1.0"
authors = ["Connor Slade <connor@connorcode.com>"]
edition = "2018"

[dependencies]
iced = { version = "0.3", features = ["smol"] }
notify-rust = "4"
msgbox = "0.6.1"
image = "0.23.14"

[build-dependencies]
chrono = "0.4.19"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"