name: CI
on: [push, pull_request]
jobs:
  buildAndTest:
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
      runs-on: ${{ matrix.os }}

      steps:
      - uses: actions/checkout@v2

      - name: Install Dependencys
        if: runner.os == 'Linux'
        run: sudo apt install libxkbcommon-dev libpango1.0-dev libatk1.0-dev libgtk-3-dev

      - name: Build
        working-directory: ./new
        run: cargo build