name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Stuff
        run: sudo apt install libxkbcommon-dev libpango1.0-dev

      - name: Build
        working-directory: ./new
        run: cargo build
